name: Release
on: { push: { branches: [ main ] } }
permissions:
  contents: write
  packages: write
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: echo "::set-output name=release::v$(git show -s --format=%ct)"
      - name: Build container
        run: |
          docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workspace -w /workspace \
            buildpacksio/pack build \
            --builder heroku/builder:24 \
            ghcr.io/${GITHUB_REPOSITORY,,}:${{ steps.data.outputs.release }}
      - name: Publish container
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${GITHUB_REPOSITORY,,}:${{ steps.data.outputs.release }}
  tag:
    runs-on: ubuntu-latest
    needs: [ container ]
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: echo "::set-output name=release::v$(git show -s --format=%ct)"
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.data.outputs.release }}
          release_name: Release ${{ steps.data.outputs.release }}
          draft: false
          prerelease: false
